services:
  jupyter-notebook-python:
    image: 'quay.io/jupyter/base-notebook:latest'
    ports:
      - 1021:8888
    environment:
      - SERVICE_URL_JUPYTER_8888
      # Configuration pour utiliser un mot de passe au lieu d'un token
      - JUPYTER_ENABLE_LAB=yes
      # Le mot de passe sera défini via la commande start-notebook.sh
    volumes:
      - '/jupyter:/home/jovyan/work'
      # Monte le répertoire de travail RAG
      - '/home/roger/RAG/ragas:/home/jovyan/work/ragas'
    command: >
      bash -c "
      # Configuration du mot de passe Jupyter
      python -c \"
      from jupyter_server.auth import passwd
      import os
      # Générer le hash du mot de passe (changez 'votre_mot_de_passe' par votre mot de passe souhaité)
      password_hash = passwd('votre_mot_de_passe')
      print('Mot de passe configuré')
      \" &&
      # Démarrer Jupyter avec la configuration
      start-notebook.sh 
      --ServerApp.token='' 
      --ServerApp.password_required=True 
      --ServerApp.password='argon2:\$argon2id\$v=19\$m=10240,t=10,p=8\$mkRGz+CKI+i2XUe9tSHIQQ\$bVZa2jOUlXmu7GVxcdngqpTG60E87fsUBtzL1OLsxjs'
      --ServerApp.allow_origin='*'
      --ServerApp.ip='0.0.0.0'
      "
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:8888/ || exit 1'
      interval: 30s
      timeout: 20s
      retries: 10